### ISSUE TITLE
Scraping breaks when moderator message is posted in thread

### ISSUE THREAD

**Issue by fekki2000** [christopherkullenberg/flashbackscraper#1]
The scraping of a thread stops (even though there are more posts)  when a moderator message is posted in the thread. For example in this thread https://www.flashback.org/t2906246p3

**Comment by christopherkullenberg** [comment]
> The scraping of a thread stops (even though there are more posts) when a moderator message is posted in the thread. For example in this thread https://www.flashback.org/t2906246p3

Hi Fekki2000,
yes, another user has also noticed this. I am working on a fix that I will push in the next few days.
Thanks for your comment!

**Comment by christopherkullenberg** [comment]
This has now been fixed by merging bengans code. Thanks a lot.
